-- ============================================================
-- 벨로르(BELLORE) · 디스코드 → 비회원 비교견적 자동 등록
-- 사용법: Supabase 대시보드 > SQL Editor 에 붙여넣고 RUN (1회)
-- 여러 번 실행해도 안전(IF NOT EXISTS / CREATE OR REPLACE).
--
-- ⚠️ 이 SQL만으로는 동작하지 않습니다. 함께 해야 하는 것:
--   ① Edge Function 재배포: 대시보드 > Edge Functions > discord-ingest 에
--      새 index.ts 내용을 붙여넣고 Deploy (재배포 안 하면 반영 안 됨)
--   ② (선택) 특정 채널만 견적으로 받으려면 Edge Functions > Secrets 에
--      DISCORD_QUOTE_CHANNELS = 채널ID,채널ID  추가 (미설정 시 수집 채널 전체)
--
-- 동작 흐름:
--   디스코드에 [사진 + 모델명] 업로드 → 2분 내 자동 수집 →
--   비회원 견적(customer_id 없음)이 status='open' 으로 즉시 생성(승인 생략) →
--   승인업체 전체 + 관리자에게 앱 알림 발송 (메일은 발송하지 않음) →
--   메시지에 100 / 1200 같은 금액(만원 단위)이 있으면
--   관리자 명의 '벨로르 1차 견적' 입찰이 자동 등록됨
-- ============================================================

-- 1) 비회원 견적 허용 — customer_id NULL 허용 -----------------
alter table public.quote_requests alter column customer_id drop not null;

-- 1-1) 상세 컬럼 보장 (quote_compare.sql 미실행 환경 대비 — 있으면 무시)
alter table public.quote_requests add column if not exists item_ref      text;
alter table public.quote_requests add column if not exists item_year     text;
alter table public.quote_requests add column if not exists item_grade    text;
alter table public.quote_requests add column if not exists item_stamping text;
alter table public.quote_requests add column if not exists item_parts    text;

-- 2) 공개(open/awarded) 견적은 로그인 사용자 누구나 조회 가능 --
--    (비회원 견적은 customer_id 가 없어 기존 '내 견적' 정책으로는
--     업체 화면에 안 보일 수 있음 → 보강. 기존 정책과 OR 로 동작해 안전)
drop policy if exists quote_requests_open_read on public.quote_requests;
create policy quote_requests_open_read on public.quote_requests
  for select to authenticated
  using (status in ('open', 'awarded'));

-- 3) notifications 테이블/컬럼 보장 (quote_notify.sql 미실행 환경 대비)
create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  type        text not null default 'info',
  title       text not null default '알림',
  body        text,
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);
create index if not exists idx_notifications_user on public.notifications(user_id, created_at desc);
alter table public.notifications add column if not exists ref_id text;

-- 4) 승인업체 알림 트리거 보장 (quote_notify.sql 과 동일 — 재실행 안전)
--    INSERT 로 바로 open 이 되는 디스코드 자동 견적에도 이 트리거가 발동해
--    승인업체 전체(role='vendor' AND approved=true)에게 알림이 간다.
create or replace function public.notify_vendors_on_open()
returns trigger language plpgsql security definer set search_path = public as $$
declare label text;
begin
  if new.status = 'open'
     and (tg_op = 'INSERT' or old.status is distinct from 'open') then
    label := coalesce(nullif(trim(coalesce(new.item_brand,'') || ' ' || coalesce(new.item_name,'')), ''), '시계');
    insert into public.notifications (user_id, type, title, body, ref_id)
    select p.id,
           'quote_open',
           '새 비교견적이 등록되었어요',
           label || ' 견적 요청이 들어왔습니다. 지금 입찰해 보세요.',
           new.id::text
      from public.profiles p
     where p.role = 'vendor'
       and p.approved = true;
  end if;
  return new;
end $$;

drop trigger if exists trg_notify_vendors_on_open on public.quote_requests;
create trigger trg_notify_vendors_on_open
  after insert or update of status on public.quote_requests
  for each row execute function public.notify_vendors_on_open();

-- 5) 관리자 알림 문구 개선 — 디스코드 자동 접수(비회원·즉시 공개)를 구분
--    (quote_compare.sql 의 notify_admin_quote 를 대체. 기존 동작은 그대로 유지)
create or replace function public.notify_admin_quote()
returns trigger
language plpgsql
security definer
set search_path = public as $$
begin
  if (TG_OP = 'INSERT' and NEW.customer_id is null and NEW.status = 'open') then
    -- 디스코드 자동 접수: 비회원 + 즉시 open
    insert into public.notifications (user_id, type, title, body, is_read, ref_id)
    select p.id, 'quote_new', '디스코드 비교견적 자동 등록',
           trim(coalesce(NEW.item_brand, '') || ' ' || coalesce(NEW.item_name, '')) ||
             ' · 비회원 자동 접수 (즉시 공개됨)',
           false, NEW.id::text
      from public.profiles p
     where lower(p.email) = lower('bellorekr@gmail.com');
  elsif (TG_OP = 'INSERT')
     or (NEW.status = 'pending' and NEW.status is distinct from OLD.status) then
    insert into public.notifications (user_id, type, title, body, is_read)
    select p.id, 'quote_new', '새 비교견적 등록(승인 대기)',
           trim(coalesce(NEW.item_brand, '') || ' ' || coalesce(NEW.item_name, '')) ||
             case when TG_OP = 'UPDATE' then ' · 수정 재승인 요청' else ' · 신규 신청' end,
           false
      from public.profiles p
     where lower(p.email) = lower('bellorekr@gmail.com');
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_notify_admin_quote on public.quote_requests;
create trigger trg_notify_admin_quote
  after insert or update on public.quote_requests
  for each row execute function public.notify_admin_quote();
