-- BELLORE My Pick
-- 찜(=내 관심)과 장바구니의 계정별 동기화 테이블.
-- 최근 본 상품은 기존 localStorage(bellore_recent_items)를 그대로 사용한다.

begin;

create table if not exists public.user_picks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  item_key text not null,
  brand text,
  model text,
  price numeric(15, 0),
  image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_picks add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.user_picks add column if not exists kind text;
alter table public.user_picks add column if not exists item_key text;
alter table public.user_picks add column if not exists brand text;
alter table public.user_picks add column if not exists model text;
alter table public.user_picks add column if not exists price numeric(15, 0);
alter table public.user_picks add column if not exists image text;
alter table public.user_picks add column if not exists created_at timestamptz not null default now();
alter table public.user_picks add column if not exists updated_at timestamptz not null default now();

-- 과거에 별도 interest 값이 저장됐다면 찜으로 합친다.
update public.user_picks
set kind = 'wish', updated_at = now()
where kind = 'interest';

-- 같은 회원·종류·상품은 한 번만 저장되어 Supabase upsert가 동작한다.
create unique index if not exists user_picks_user_kind_item_uidx
  on public.user_picks (user_id, kind, item_key);

create index if not exists user_picks_user_kind_created_idx
  on public.user_picks (user_id, kind, created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.user_picks'::regclass
      and conname = 'user_picks_kind_check'
  ) then
    alter table public.user_picks
      add constraint user_picks_kind_check
      check (kind in ('wish', 'cart'));
  end if;
end
$$;

create or replace function public.touch_user_picks_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_user_picks_updated_at on public.user_picks;
create trigger trg_user_picks_updated_at
before update on public.user_picks
for each row execute function public.touch_user_picks_updated_at();

alter table public.user_picks enable row level security;

drop policy if exists "user_picks_select_own" on public.user_picks;
create policy "user_picks_select_own"
on public.user_picks for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_picks_insert_own" on public.user_picks;
create policy "user_picks_insert_own"
on public.user_picks for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_picks_update_own" on public.user_picks;
create policy "user_picks_update_own"
on public.user_picks for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_picks_delete_own" on public.user_picks;
create policy "user_picks_delete_own"
on public.user_picks for delete
to authenticated
using (auth.uid() = user_id);

grant select, insert, update, delete on public.user_picks to authenticated;
do $$
begin
  if to_regclass('public.user_picks_id_seq') is not null then
    execute 'grant usage, select on sequence public.user_picks_id_seq to authenticated';
  end if;
end
$$;

comment on table public.user_picks is
  'BELLORE 보관함. kind=wish는 찜과 내 관심에서 동일하게 사용하고 kind=cart는 장바구니다.';

commit;
