-- ============================================================
-- 벨로르(BELLORE) · 알림 정리 + 트리거 보장
-- Supabase 대시보드 > SQL Editor 에 "통째로" 붙여넣고 RUN
--
-- 왜 필요한가:
--   - 예전에 만들어진 "산토스", "오", "츠" 처럼 본문만 짧게 남은
--     알 수 없는 옛날 알림을 정리합니다(어떤 알림인지/어디로 가는지 모르는 것).
--   - 앞으로의 알림은 bid_notify.sql / quote_notify.sql 트리거가
--     "제목 + 어떤 시계 / 얼마 + 바로가기(ref_id)" 를 항상 채웁니다.
--
-- ※ 이 파일 실행 후, 아직 안 했다면 quote_notify.sql 과 bid_notify.sql 도 실행하세요.
-- ============================================================

-- 0) 알림 테이블/참조컬럼 보장(신규 환경 대비, 이미 있으면 무시)
create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  type        text not null default 'info',
  title       text not null default '알림',
  body        text,
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);
alter table public.notifications add column if not exists ref_id text;

-- 1) 알 수 없는 옛날 알림 정리
--    - 알려진 종류가 아닌 것(type 이 아래 목록에 없음) 이면서
--    - 본문이 비어 있거나 8자 미만으로 무슨 알림인지 알 수 없는 것
delete from public.notifications n
 where coalesce(n.type,'') not in
   ('quote_open','quote_new','bid_new','awarded','approved',
    'account','business','listing','settlement','support_new','support_reply','info')
   and (n.body is null or char_length(trim(n.body)) < 8);

-- 2) (선택) 본문이 비어 제목만 있는 알림에 기본 안내 채우기
update public.notifications
   set body = '내역을 확인해 주세요.'
 where (body is null or trim(body) = '')
   and title is not null and trim(title) <> '';
