-- ============================================================
-- 벨로르(BELLORE) · 새 비교견적(open) 발생 시 승인업체 자동 알림
-- 사용법: Supabase 대시보드 > SQL Editor 에 붙여넣고 RUN (1회)
--
-- 동작:
--   - 관리자가 비교견적을 승인하면 quote_requests.status 가 'open' 으로 바뀝니다.
--   - 이때 승인된 모든 업체(profiles.role='vendor' AND approved=true)에게
--     notifications 알림을 자동 생성합니다. (마이페이지 벨 + 실시간 배지)
--   - 그동안 코드 주석에만 있고 실제로는 없던 "트리거가 알림" 부분을 채웁니다.
--
-- ⚠️ 이메일/푸시가 아니라 '사이트 내 알림(notifications)' 입니다.
--    메일 발송은 별도 Edge Function(B단계)에서 처리합니다.
-- ============================================================

-- 0) notifications 테이블 보장(이미 있으면 무시) — 신규 환경 대비
create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  type        text not null default 'info',
  title       text not null default '알림',
  body        text,
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);
create index if not exists idx_notifications_user on public.notifications(user_id, created_at desc);

-- 1) 트리거 함수: open 전환 시 승인업체 전체에게 알림 insert
create or replace function public.notify_vendors_on_open()
returns trigger language plpgsql security definer set search_path = public as $$
declare label text;
begin
  -- INSERT로 바로 open 이거나, UPDATE로 open 으로 바뀐 경우에만
  if new.status = 'open'
     and (tg_op = 'INSERT' or old.status is distinct from 'open') then

    label := coalesce(nullif(trim(coalesce(new.item_brand,'') || ' ' || coalesce(new.item_name,'')), ''), '시계');

    insert into public.notifications (user_id, type, title, body)
    select p.id,
           'quote_open',
           '새 비교견적이 등록되었어요',
           label || ' 견적 요청이 들어왔습니다. 지금 입찰해 보세요.'
      from public.profiles p
     where p.role = 'vendor'
       and p.approved = true;
  end if;
  return new;
end $$;

-- 2) 트리거 연결 (중복 방지 위해 drop 후 재생성)
drop trigger if exists trg_notify_vendors_on_open on public.quote_requests;
create trigger trg_notify_vendors_on_open
  after insert or update of status on public.quote_requests
  for each row execute function public.notify_vendors_on_open();
